[package]
name = "major-requirement-parser"
version = "0.1.3"
edition = "2024"

[[bin]]
name = "mql"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
libmql = { path = "../libmql" }
