[package]
name = "major-requirement-parser-cli"
version = "0.1.6"
edition = "2024"
default-run = "mql"

[[bin]]
name = "mql"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
libmql = { path = "../libmql" }
